spring:  
  profiles:
    # Comma-separated list of active profiles.
    #active: predix-basic
    active: local

---

spring:
  profiles: local
  
server:
  port: 8080

#${vcap.services.postgres.credentials.jdbc_uri}
redis:
  host : 10.72.6.33
  port : 59264
  password : 899a6b75-749e-4b10-ba5d-da2becd82f5e


---

spring:
  profiles: predix-basic
  
server:
  port: ${PORT}

redis:
  host : 10.72.6.33
  port : 59264
  password : 899a6b75-749e-4b10-ba5d-da2becd82f5e

---
spring:
  profiles: predix-select
#${vcap.services.postgres.credentials.jdbc_uri}
redis:
  host : ${vcap.services.redis-17.credentials.host}
  port : ${vcap.services.redis-17.credentials.port}
  password : ${vcap.services.redis-17.credentials.password}
#  "redis-17": [
#  {
#   "credentials": {
#    "host": "10.72.6.33",
#    "password": "899a6b75-749e-4b10-ba5d-da2becd82f5e",
#    "port": 59264
#   },s