spring:  
  profiles:
    # Comma-separated list of active profiles.
    #active: predix-basic
    active: local

---

spring:
  profiles: local
  
server:
  port: 8080

redis:
  host : yourlocal
  port : 1111
  password : yourlocal


---

spring:
  profiles: predix-basic
  
server:
  port: ${PORT}

redis:
  host : change
  port : 111111
  password : change
